steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - run
      - "--privileged"
      - "multiarch/qemu-user-static"
      - "--reset -p yes"
  - name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - inspect
      - "--bootstrap"
  - name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - create
      - "--use"
      - "--name"
      - build
  - name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - build
      - "--platform"
      - $_DOCKER_BUILDX_PLATFORMS
      - "-t"
      - "gcr.io/$PROJECT_ID/pihole-unbound:latest"
      - "--push"
      - .
options:
  env:
    - DOCKER_CLI_EXPERIMENTAL=enabled
substitutions:
  _DOCKER_BUILDX_PLATFORMS: "linux/arm/v7,linux/arm64/v8,linux/amd64"
