steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - create
      - "--use"
      - "--name"
      - build
  - name: gcr.io/cloud-builders/docker
    args:
      - buildx
      - build
      - "--platform"
      - $_DOCKER_BUILDX_PLATFORMS
      - "-t"
      - "gcr.io/$PROJECT_ID/pihole-unbound:latest"
      - "--push"
      - .
options:
  env:
    - DOCKER_CLI_EXPERIMENTAL=enabled
substitutions:
  _DOCKER_BUILDX_PLATFORMS: "linux/amd64,linux/arm64"
